library(dplyr)
data =read.csv("C:/Users/Heathtasia/Downloads/recs2009_public.csv")
attach(data)
data1=filter(data,TYPEHUQ==2)
data2=group_by(data1,REPORTABLE_DOMAIN,CELLAR)
data3=summarise(data2, n=n() ) ##n=n() counting,, n=sum(NWEIGHT)
data4=mutate(data3,f=n/sum(n))
data5=filter(data4,CELLAR==1)
data6=ungroup(data5)
data7=arrange(data6,f)
data8=select(data8,-CELLAR)
data9=arrange(data6,-f)
data10=arrange(data6,desc(f))