library(dplyr)
data2 =read.csv("E:/MA 2015/STAT506ps2_1.csv",header=FALSE)
index<-duplicated(data2$Id)
data2=data2[!index,]
data2$State=gsub("\t","",data2$State)
data2$State=gsub("\\'","",data2$State)
data2$State=gsub(" ","",data2$State)
data2$State=gsub("\\(","",data2$State)
data2$State=gsub("\\)","",data2$State)
data2$State=gsub("\"","",data2$State)
data2$State=toupper(data2$State)
data2$State=gsub("HAWAII","HI",data2$State)
data2$State=gsub("KANSAS","KS",data2$State)
data2$State=gsub("ARIZONA","AZ",data2$State)
data2$State=gsub("CONN","CT",data2$State)
data2$State=gsub("CTCT","CT",data2$State)
data2$State=gsub("CALIF","CA",data2$State)
data2$State=gsub("MICH","MI",data2$State)
data2$State=gsub("IND","IN",data2$State)
ata2$State=gsub("HA","HI",data2$State)
data2$State=gsub("UNKNOWN",NA,data2$State)
data2$State=gsub("OTHER",NA,data2$State)
data2$State=gsub("IAKS",NA,data2$State)
data2$State=gsub("AD",NA,data2$State)
data2$State=gsub("OI",NA,data2$State)
data2$State=gsub("IB",NA,data2$State)
gb=group_by(data2,State)
su<-summarize(gb,Mean=mean(weight),Variance=var(weight),n=n())