library(foreign)
dental<-read.xport("C:/Users/Heathtasia/Desktop/OHXDEN_F.XPT")
dgraphic<-read.xport("C:/Users/Heathtasia/Desktop/DEMO_F.XPT")
dentaldata<-inner_join(dental,dgraphic,by="SEQN")
dentaldata$age <- dentaldata$RIDAGEEX %/% 12
dgb=group_by(dentaldata,age)
par(mfrow=c(4,8))
test_try<-summarize(dgb,Percentage=length(OHX01TC[OHX01TC==2])/length(OHX01TC)-mean(is.na(OHX02TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX01")
test_try<-summarize(dgb,Percentage=length(OHX02TC[OHX02TC==2])/length(OHX02TC)-mean(is.na(OHX02TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX02")
test_try<-summarize(dgb,Percentage=length(OHX03TC[OHX03TC==2])/length(OHX03TC)-mean(is.na(OHX03TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX03")
test_try<-summarize(dgb,Percentage=length(OHX04TC[OHX04TC==2])/length(OHX04TC)-mean(is.na(OHX04TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX04")
test_try<-summarize(dgb,Percentage=length(OHX05TC[OHX05TC==2])/length(OHX05TC)-mean(is.na(OHX05TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX05")
test_try<-summarize(dgb,Percentage=length(OHX06TC[OHX06TC==2])/length(OHX06TC)-mean(is.na(OHX06TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX06")
test_try<-summarize(dgb,Percentage=length(OHX07TC[OHX07TC==2])/length(OHX07TC)-mean(is.na(OHX07TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX07")
test_try<-summarize(dgb,Percentage=length(OHX08TC[OHX08TC==2])/length(OHX08TC)-mean(is.na(OHX08TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX08")
test_try<-summarize(dgb,Percentage=length(OHX09TC[OHX09TC==2])/length(OHX09TC)-mean(is.na(OHX09TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX09")
test_try<-summarize(dgb,Percentage=length(OHX10TC[OHX10TC==2])/length(OHX10TC)-mean(is.na(OHX10TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX10")
test_try<-summarize(dgb,Percentage=length(OHX11TC[OHX11TC==2])/length(OHX11TC)-mean(is.na(OHX11TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX11")
test_try<-summarize(dgb,Percentage=length(OHX12TC[OHX12TC==2])/length(OHX12TC)-mean(is.na(OHX12TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX12")
test_try<-summarize(dgb,Percentage=length(OHX13TC[OHX13TC==2])/length(OHX13TC)-mean(is.na(OHX13TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX13")
test_try<-summarize(dgb,Percentage=length(OHX14TC[OHX14TC==2])/length(OHX14TC)-mean(is.na(OHX14TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX14")
test_try<-summarize(dgb,Percentage=length(OHX15TC[OHX15TC==2])/length(OHX15TC)-mean(is.na(OHX15TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX15")
test_try<-summarize(dgb,Percentage=length(OHX16TC[OHX16TC==2])/length(OHX16TC)-mean(is.na(OHX16TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX16")
test_try<-summarize(dgb,Percentage=length(OHX17TC[OHX17TC==2])/length(OHX17TC)-mean(is.na(OHX17TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX17")
test_try<-summarize(dgb,Percentage=length(OHX18TC[OHX18TC==2])/length(OHX18TC)-mean(is.na(OHX18TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX18")
test_try<-summarize(dgb,Percentage=length(OHX19TC[OHX19TC==2])/length(OHX19TC)-mean(is.na(OHX19TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX19")
test_try<-summarize(dgb,Percentage=length(OHX20TC[OHX20TC==2])/length(OHX20TC)-mean(is.na(OHX20TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX20")
test_try<-summarize(dgb,Percentage=length(OHX21TC[OHX21TC==2])/length(OHX21TC)-mean(is.na(OHX21TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX21")
test_try<-summarize(dgb,Percentage=length(OHX22TC[OHX22TC==2])/length(OHX22TC)-mean(is.na(OHX22TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX22")
test_try<-summarize(dgb,Percentage=length(OHX23TC[OHX23TC==2])/length(OHX23TC)-mean(is.na(OHX23TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX23")
test_try<-summarize(dgb,Percentage=length(OHX24TC[OHX24TC==2])/length(OHX24TC)-mean(is.na(OHX24TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX24")
test_try<-summarize(dgb,Percentage=length(OHX25TC[OHX25TC==2])/length(OHX25TC)-mean(is.na(OHX25TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX25")
test_try<-summarize(dgb,Percentage=length(OHX26TC[OHX26TC==2])/length(OHX26TC)-mean(is.na(OHX26TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX26")
test_try<-summarize(dgb,Percentage=length(OHX27TC[OHX27TC==2])/length(OHX27TC)-mean(is.na(OHX27TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX27")
test_try<-summarize(dgb,Percentage=length(OHX28TC[OHX28TC==2])/length(OHX28TC)-mean(is.na(OHX28TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX28")
test_try<-summarize(dgb,Percentage=length(OHX29TC[OHX29TC==2])/length(OHX29TC)-mean(is.na(OHX29TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX29")
test_try<-summarize(dgb,Percentage=length(OHX30TC[OHX30TC==2])/length(OHX30TC)-mean(is.na(OHX30TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX30")
test_try<-summarize(dgb,Percentage=length(OHX31TC[OHX31TC==2])/length(OHX31TC)-mean(is.na(OHX31TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX31")
test_try<-summarize(dgb,Percentage=length(OHX32TC[OHX31TC==2])/length(OHX32TC)-mean(is.na(OHX32TC)),n=n())
plot(test_try$age,test_try$Percentage,xlab="Age",ylab="Existing Percentage",main="OHX32")



