library(faraway)
data(uswages)
attach(uswages)
help(uswages)
summary(uswages)
hist(uswages$wage,main="Distribution of Weekly Wage",xlab="Weekly Wage in dollars")
uswages$race=factor(uswages$race)
levels(uswages$race)=c("white","black")
uswages$pt=factor(uswages$pt)
levels(uswages$pt)=c("no","yes")
uswages$smsa=factor(uswages$smsa)
levels(uswages$smsa)=c("no","yes")
uswages$location[uswages$ne==1]=1
uswages$location[uswages$mw==1]=2
uswages$location[uswages$so==1]=3
uswages$location[uswages$we==1]=4
uswages$location=factor(uswages$location)
levels(uswages$location)=c("ne","mw","so","we")
sort(uswages$exper)
uswages$exper[uswages$exper<0] <- NA
hist(uswages$race,main="Distribution of Race")
hist(uswages$smsa,main="Living in SMSA or Not")
hist(uswages$pt,main="Working Part-time or Not")
hist(uswages$educ,main="Distribution of Education",xlab="Years of Education")
hist(uswages$exper,main="Distribution of Experience",xlab="Years of Experience")
hist(uswages$location,main="Distribution of Location",xlab="Location")
plot(factor(educ),wage,xlab="Years of Education",ylab="Weekly Wage in dollars")
plot(exper,wage,xlab="Years of Experience",ylab="Weekly Wage in dollars")
plot(uswages$location,uswages$wage,xlab="Location",ylab="Weekly Wage in dollars")
plot(uswages$race,uswages$wage,xlab="Race",ylab="Weekly Wage in dollars")
plot(uswages$educ,uswages$wage,xlab="Years of Education",ylab="Weekly Wage in dollars")
plot(factor(uswages$educ),uswages$wage,xlab="Years of Education",ylab="Weekly Wage in dollars")
plot(factor(uswages$exper),uswages$wage,xlab="Years of Experience",ylab="Weekly Wage in dollars")
plot(factor(uswages$smsa),uswages$wage,xlab="Living in SMSA",ylab="Weekly Wage in dollars")
plot(factor(uswages$pt),uswages$wage,xlab="Working part-time",ylab="Weekly Wage in dollars")
####
uswages$wage[uswages$wage>2000] <- NA
plot(uswages$location)
plot(uswages$location,main="Distribution of Location")
plot(uswages$location,main="Distribution of Location",xlab="Location")
plot(uswages$race,main="Distribution of Race",xlab="race")
plot(uswages$smsa,main="Living in SMSA or Not",xlab="Living in Standard Metropolitan Statistical Area")
plot(uswages$pt,main="Working Part-time or Not",xlab="Working Part-time")
plot(uswages$pt,main="Working Part-time or Not",xlab="Working Part-time")
plot(uswages$location,wage,xlab="Location",ylab="Weekly Wage in dollars")
plot(uswages$location,uswages$wage,xlab="Location",ylab="Weekly Wage in dollars")
plot(uswages$race,uswages$wage,xlab="Race",ylab="Weekly Wage in dollars")
plot(uswages$educ,uswages$wage,xlab="Years of Education",ylab="Weekly Wage in dollars")
plot(factor(uswages$educ),uswages$wage,xlab="Years of Education",ylab="Weekly Wage in dollars")
plot(factor(uswages$exper),uswages$wage,xlab="Years of Experience",ylab="Weekly Wage in dollars")
plot(factor(uswages$smsa),uswages$wage,xlab="Living in SMSA",ylab="Weekly Wage in dollars")
plot(factor(uswages$pt),uswages$wage,xlab="Working part-time",ylab="Weekly Wage in dollars")
plot(factor(uswages$location),uswages$wage,xlab="Location",ylab="Weekly Wage in dollars")
plot(factor(uswages$location),uswages$exper,xlab="Location",ylab="Years of Experience")
plot(factor(uswages$location),uswages$educ,xlab="Location",ylab="Years of Education")
plot(factor(uswages$location),uswages$race,xlab="Location",ylab="Race")
plot(factor(uswages$location),uswages$smsa,xlab="Location",ylab="Living in SMSA")
plot(factor(uswages$location),uswages$pt,xlab="Location",ylab="Working Part-time")
plot(factor(uswages$race),uswages$educ,xlab="Race",ylab="Years of Education")
plot(factor(uswages$race),uswages$exper,xlab="Race",ylab="Years of Experience")
plot(factor(uswages$race),uswages$pt,xlab="Race",ylab="Working Part-time")
plot(factor(uswages$race),uswages$smsa,xlab="Race",ylab="Living in SMSA")
plot(factor(uswages$smsa),uswages$educ,xlab="Living in SMSA",ylab="Years of Education")
plot(factor(uswages$smsa),uswages$exper,xlab="Living in SMSA",ylab="Years of Experience")
plot(factor(uswages$smsa),uswages$pt,xlab="Living in SMSA",ylab="Working Part-time")
plot(factor(uswages$educ),uswages$pt,xlab="Years of Education",ylab="Working Part-time")
plot(factor(uswages$pt),uswages$educ,xlab="Living in SMSA",ylab="Working Part-time")
plot(factor(uswages$pt),uswages$educ,xlab="Working Part-time",ylab="Years of Education")
plot(factor(uswages$pt),uswages$exper,xlab="Working Part-time",ylab="Years of Experience")
plot(factor(uswages$pt),uswages$educ,xlab="Working Part-time",ylab="Years of Education")
plot(factor(uswages$smsa),uswages$race,xlab="Working Part-time",ylab="Years of Education")
plot(factor(uswages$pt),uswages$race,xlab="Working Part-time",ylab="Years of Education")
 
