library(faraway)
data(teengamb)
attach(teengamb)
tg.reg=lm(gamble~sex+status+income+verbal,teengamb)
summary(lm(abs(tg.reg$residuals)~tg.reg$fitted.values))
par(mfrow=c(1,2),oma=c(0,0,3,0))
plot(tg.reg$fitted,tg.reg$residuals,xlab="Fitted",ylab="Residuals")
abline(h=0)
plot(tg.reg$fitted,abs(tg.reg$residuals),lty=2,xlab="Fitted",ylab="|Residuals|")
mtext("Teengamb Ctd",side=3,line=0,outer=T)
tg.moreg=lm(sqrt(gamble)~sex+status+income+verbal,teengamb)
par(mfrow=c(1,2),oma=c(0,0,3,0))
plot(tg.moreg$fitted,tg.moreg$residuals,xlab="Fitted",ylab="Residuals")
plot(tg.moreg$fitted,abs(tg.moreg$residuals),xlab="Fitted",ylab="|Residuals|")
mtext("Modified Teengamb Ctd",side=3,line=0,outer=T)
summary(lm(abs(tg.moreg$residuals)~tg.moreg$fitted.values))
qqnorm(tg.moreg$residuals,ylab="Residuals",main="")
qqline(tg.moreg$residuals)
hist(tg.moreg$residuals,xlab="Residuals",main="")
mtext("QQ-plot and Hist-plot",side=3,line=0,outer=T)
reg<-lm(gamble~.,data=teengamb)
halfnorm(lm.influence(reg)$hat,nlab=2,ylab="Leverages",main="Half-normal Plot")
teengamb[c(35,42),]
ti <- rstudent(tg.moreg)
max(abs(ti))
which(ti == max(abs(ti)))
2*(1-pt(max(abs(ti)),df=47-5-1))
0.05/47
library(DMwR)
outlier.scores<-lofactor(teengamb,k=5)
plot(density(outlier.scores))
outliers <- order(outlier.scores, decreasing=T)[1:5]
print(outliers)
halfnorm(cook,nlab=3,ylab="Cook's distance",main="Cook's Distance")
tg.moreg.24<-lm(gamble~sex+status+income+verbal,data=teengamb,subset=(cook<max(cook)))
plot(tg.moreg.inf$coef[,2],tg.moreg.inf$coef[,3],xlab="Change in beta2",ylab="Change in beta3",main="Changes in Coefficients")
identify(tg.moreg.inf$coef[,2],tg.moreg.inf$coef[,3])