library(faraway)
attach(trees)
library(MASS)
g<-lm(Volume~Girth+Height,trees)
boxcox(g,plotit=T,lambda=seq(0,0.6,by=0.1))
trees$v1=(Volume^0.31-1)/0.31
g1<-lm(v1~Girth+Height,trees)
plot(g$fitted,g$residuals,xlab="Fitted",ylab="Residuals",main="Original Model")
plot(g1$fitted,g1$residuals,xlab="Fitted",ylab="Residuals",main="Transformed Model")
g2<-lm(Volume~Girth+Height+I(Girth^2)+I(Height^2)+I(Girth*Height),trees)
g21<-lm(Volume~Girth+Height+I(Girth^2)+I(Girth*Height),trees)
g22<-lm(Volume~Girth+Height+I(Girth^2),trees)
g3<-lm(v1~Girth+Height+I(Girth^2)+I(Height^2)+I(Girth*Height),trees)
g31<-lm(v1~Girth+Height+I(Girth^2)+I(Height^2),trees)
g32<-lm(v1~Girth+Height+I(Height^2),trees)
