library(faraway)
data(prostate)
attach(prostate)
g=lm(lpsa~.,data=prostate)
summary(g)
g=update(g,.~.-gleason)
summary(g)
g=update(g,.~.-lcp)
summary(g)
g=update(g,.~.-pgg45)
summary(g)
g=update(g,.~.-age)
summary(g)
g=update(g,.~.-lbph)
summary(g)
g=lm(lpsa~.,data=prostate)
step(g)
library(leaps)
b=regsubsets(lpsa~.,data=prostate)
rs=summary(b)
plot(2:9,rs$adjr2,xlab="No. of Parameters",ylab="Adjusted Rsq")
which.max(rs$adjr2)
which.min(rs$cp)
plot(2:9,rs$cp,xlab="No. of Parameters",ylab="Cp")
abline(0,1)
